import {SELF,runInDurableObject,evictDurableObject} from "cloudflare:test";
import {env} from "cloudflare:workers";
import type {Env} from "../src/env";
import type {Room} from "../src/room";
import {parseClientMessage} from "../src/protocol";
import {describe,it,expect,vi} from "vitest";
async function open(room:string){
  const res=await SELF.fetch(`https://game.test/ws/${room}`,{headers:{Upgrade:"websocket"}});expect(res.status).toBe(101);const ws=res.webSocket!;ws.accept();const frames:any[]=[];
  ws.addEventListener("message",(event:MessageEvent)=>{if(typeof event.data==="string"&&event.data!=="__pong")frames.push(JSON.parse(event.data));});
  const next=async(pred:(f:any)=>boolean)=>{for(let i=0;i<150;i++){const index=frames.findIndex(pred);if(index!==-1)return frames.splice(index,1)[0];await scheduler.wait(10);}throw new Error(`timed out; ${JSON.stringify(frames).slice(0,1000)}`);};
  return {ws,frames,next,send:(m:unknown)=>ws.send(JSON.stringify(m)),state:()=>next(f=>f.type==="state"),error:()=>next(f=>f.type==="error"),action:(action:unknown)=>ws.send(JSON.stringify({type:"action",action}))};
}
const uniq=()=>`test-${crypto.randomUUID().slice(0,12)}`;
async function join(room:string,name="Pilot"){const c=await open(room);c.send({type:"join",name});const welcome=await c.next(f=>f.type==="welcome");const state=await c.state();return {...c,id:welcome.playerId,token:welcome.token,initial:state};}
async function ready(c:Awaited<ReturnType<typeof join>>){c.action({type:"ready",ready:true});await c.next(f=>f.type==="state"&&f.view.players.find((p:any)=>p.id===c.id)?.ready);}
describe("real Workers WebSockets",()=>{
  it("keeps lobby persistent and starts only after ready + host start",async()=>{const room=uniq();const a=await join(room,"Alpha"),b=await join(room,"Beta");expect(a.initial.status).toBe("lobby");expect(b.initial.view.players).toHaveLength(2);expect(b.initial.meta.game).toBe("Novaris: Fleet Vanguard");b.action({type:"start"});expect((await b.error()).error).toMatch(/host/);a.action({type:"start"});expect((await a.error()).error).toMatch(/ready/);await ready(a);await ready(b);a.action({type:"start"});const active=await a.next(f=>f.type==="state"&&f.status==="playing");expect(active.view.npcs).toHaveLength(15);await b.next(f=>f.type==="state"&&f.status==="playing");const tick=await a.next(f=>f.type==="state"&&f.view.tick>0);expect(tick.view.tick).toBeGreaterThan(0);a.ws.close();b.ws.close();});
  it("rejects impersonation and restores only the token holder's seat",async()=>{const room=uniq(),a=await join(room,"Alpha"),b=await join(room,"Beta");const thief=await open(room);thief.send({type:"join",playerId:a.id});expect((await thief.error()).error).toMatch(/token/);expect(JSON.stringify(b.initial)).not.toContain(a.token);a.ws.close();const again=await open(room);again.send({type:"join",playerId:a.id,token:a.token});expect((await again.next(f=>f.type==="welcome")).playerId).toBe(a.id);const restored=await again.state();expect(restored.seats).toEqual([a.id,b.id]);expect(restored.view.players.find((p:any)=>p.id===a.id).name).toBe("Alpha");again.ws.close();b.ws.close();thief.ws.close();});
  it("blocks server tick injection, malformed movement and nonhost resets",async()=>{const room=uniq(),a=await join(room),b=await join(room);await ready(a);await ready(b);a.action({type:"start"});await a.next(f=>f.type==="state"&&f.status==="playing");a.action({type:"tick"});expect((await a.error()).error).toMatch(/unknown action/);a.action({type:"input",mx:999,my:0,mz:0,yaw:0,pitch:0,fire:true,boost:false});expect((await a.error()).error).toMatch(/range/);b.send({type:"reset"});expect((await b.error()).error).toMatch(/host/);a.send({type:"reset"});const lobby=await a.next(f=>f.type==="state"&&f.status==="lobby"&&f.view.players.every((p:any)=>!p.ready));expect(lobby.view.tick).toBe(0);a.ws.close();b.ws.close();});
  it("broadcasts authoritative movement to two players and supports late joins",async()=>{const room=uniq(),a=await join(room);await ready(a);a.action({type:"start"});await a.next(f=>f.type==="state"&&f.status==="playing");const b=await join(room);expect(b.initial.status).toBe("playing");const old=b.initial.view.players.find((p:any)=>p.id===a.id).x;a.action({type:"input",mx:1,my:0,mz:0,yaw:0,pitch:0,fire:false,boost:false});const moved=await b.next(f=>f.type==="state"&&f.view.players.find((p:any)=>p.id===a.id).x>old);expect(moved.view.players).toHaveLength(2);a.ws.close();const left=await b.next(f=>f.type==="state"&&f.connected===1);expect(left.view.hostId).toBe(b.id);expect(left.view.players.find((p:any)=>p.id===a.id).connected).toBe(false);b.ws.close();});
  it("isolates rooms and rejects malformed frames before persistence",async()=>{const a=await join(uniq()),b=await join(uniq());expect(a.initial.seats).toEqual([a.id]);expect(b.initial.seats).toEqual([b.id]);a.ws.send("bad JSON");expect((await a.error()).error).toBe("invalid json");a.send({type:"action",action:{blob:"x".repeat(20000)}});expect((await a.error()).error).toBe("message too large");a.ws.close();b.ws.close();});
  it("caps rooms at six players",async()=>{const room=uniq(),all=[];for(let i=0;i<6;i++)all.push(await join(room));const extra=await open(room);extra.send({type:"join"});expect((await extra.error()).error).toMatch(/full/);for(const c of all)c.ws.close();extra.ws.close();});
  it("requires joining before actions and rejects nonupgrade websocket paths",async()=>{const c=await open(uniq());c.action({type:"ready",ready:true});expect((await c.error()).error).toBe("join first");c.ws.close();const res=await SELF.fetch("https://game.test/ws");expect(res.status).toBe(426);});
  it("migrates host after everyone leaves and does not let a stale token connection steal it",async()=>{
    const room=uniq(),a=await join(room,"Former host");a.ws.close();await scheduler.wait(30);const b=await join(room,"New host");expect(b.initial.view.hostId).toBe(b.id);await ready(b);b.action({type:"start"});await b.next(f=>f.type==="state"&&f.status==="playing");const old=await open(room);old.send({type:"join",playerId:a.id,token:a.token});await old.next(f=>f.type==="welcome");expect((await old.state()).view.hostId).toBe(b.id);old.ws.close();b.ws.close();
  });
  it("releases an offline seat in a full lobby and invalidates only its old token",async()=>{
    const room=uniq(),all=[];for(let i=0;i<6;i++)all.push(await join(room,"Pilot "+i));const host=all[0]!,gone=all[1]!,peer=all[2]!;
    host.action({type:"dismiss",playerId:peer.id});expect((await host.error()).error).toMatch(/offline/);
    gone.ws.close();await host.next(f=>f.type==="state"&&f.view.players.find((p:any)=>p.id===gone.id)?.connected===false);
    peer.action({type:"dismiss",playerId:gone.id});expect((await peer.error()).error).toMatch(/host/);
    host.action({type:"dismiss",playerId:gone.id});const state=await host.next(f=>f.type==="state"&&f.seats.length===5&&!f.seats.includes(gone.id));expect(state.seats).not.toContain(gone.id);
    const stale=await open(room);stale.send({type:"join",playerId:gone.id,token:gone.token});expect((await stale.error()).error).toBe("unknown reconnect identity");const replacement=await join(room,"Replacement");expect(replacement.initial.seats).toHaveLength(6);expect(replacement.id).not.toBe(gone.id);
    for(const c of all)c.ws.close();replacement.ws.close();stale.ws.close();
  });
  it("supersedes a socket on token reconnect without disconnecting the replacement",async()=>{
    const room=uniq(),a=await join(room),replacement=await open(room);replacement.send({type:"join",playerId:a.id,token:a.token});await replacement.next(f=>f.type==="welcome");const restored=await replacement.state();expect(restored.connected).toBe(1);await scheduler.wait(30);replacement.action({type:"ready",ready:true});expect((await replacement.next(f=>f.type==="state"&&f.view.players[0].ready)).view.players[0].connected).toBe(true);replacement.ws.close();
  });
  it("rate limits action floods without preventing later ordinary input",async()=>{
    const a=await join(uniq());for(let i=0;i<48;i++)a.action({type:"ready",ready:true});expect((await a.next(f=>f.type==="error"&&f.error==="too many messages")).error).toBe("too many messages");await scheduler.wait(1020);a.action({type:"ready",ready:false});expect((await a.next(f=>f.type==="state"&&f.view.players[0].ready===false)).status).toBe("lobby");a.ws.close();
  });

  it("completes the close handshake for both joined and unjoined sockets",async()=>{
    for(const joined of [false,true]){const c=joined?await join(uniq()):await open(uniq());let closed=false;c.ws.addEventListener("close",()=>{closed=true;});c.ws.close(1000,"Done");for(let attempt=0;attempt<20&&!closed;attempt++)await scheduler.wait(10);expect(closed).toBe(true);}
  });

  it("exposes a transient alarm failure and preserves the reconnectable room after reset",async()=>{
    const name=uniq(),a=await join(name,"Preserved pilot");const binding=(env as unknown as Env).ROOMS;const stub=binding.get(binding.idFromName(name));
    await expect(runInDurableObject(stub,async(instance)=>{
      const room=instance as Room;const load=vi.spyOn(room as any,"load").mockRejectedValueOnce(new Error("temporary storage failure"));const log=vi.spyOn(console,"error").mockImplementation(()=>{});
      try{await room.alarm();}finally{load.mockRestore();log.mockRestore();}
    })).rejects.toThrow("temporary storage failure");
    const newcomer=await join(name,"After reset");expect(newcomer.initial.view.hostId).toBe(newcomer.id);
    const replacement=await open(name);replacement.send({type:"join",playerId:a.id,token:a.token});expect((await replacement.next(f=>f.type==="welcome")).playerId).toBe(a.id);expect((await replacement.state()).view.players[0].name).toBe("Preserved pilot");a.ws.close();replacement.ws.close();newcomer.ws.close();
  });

  it("rejects deeply nested action frames without throwing inside the room gate",()=>{
    const raw='{"type":"action","action":{"x":'+"[".repeat(7900)+"0"+"]".repeat(7900)+'}}';expect(new TextEncoder().encode(raw).length).toBeLessThan(16384);expect(()=>parseClientMessage(raw)).not.toThrow();expect(parseClientMessage(raw).ok).toBe(false);
  });

  // Trusted fixture isolates an interaction race; no fixture is used by the complete live PvP checker.
  it("serializes simultaneous core claims so only one pilot receives the point",async()=>{
    const name=uniq(),a=await join(name),b=await join(name);await ready(a);await ready(b);a.action({type:"start"});await a.next(f=>f.type==="state"&&f.status==="playing");
    const binding=(env as unknown as Env).ROOMS;await runInDurableObject(binding.get(binding.idFromName(name)),async(_instance,ctx)=>{const game:any=await ctx.storage.get("game");game.state.npcs=[];for(const p of game.state.players)Object.assign(p,{zone:"ember",x:0,y:0,z:28});await ctx.storage.put("game",game);});
    a.action({type:"interact",targetId:"core:ember"});b.action({type:"interact",targetId:"core:ember"});const result=await a.next(f=>f.type==="state"&&f.view.objective.cores.includes("ember"));expect(result.view.objective.cores).toEqual(["ember"]);expect(result.view.players.reduce((n:number,p:any)=>n+p.score,0)).toBe(1);for(let i=0;i<30&&!a.frames.concat(b.frames).some(f=>f.type==="error");i++)await scheduler.wait(10);expect(a.frames.concat(b.frames).some(f=>f.type==="error"&&f.error.includes("not available"))).toBe(true);a.ws.close();b.ws.close();
  });
  // Trusted death fixture tests reconnect invariants without waiting for an unrelated combat sequence.
  it("keeps a defeated pilot dead and preserves the new host when reconnecting during combat",async()=>{
    const name=uniq(),a=await join(name),b=await join(name);await ready(a);await ready(b);a.action({type:"start"});await a.next(f=>f.type==="state"&&f.status==="playing");
    const binding=(env as unknown as Env).ROOMS;await runInDurableObject(binding.get(binding.idFromName(name)),async(_instance,ctx)=>{const game:any=await ctx.storage.get("game");const p=game.state.players.find((p:any)=>p.id===a.id);Object.assign(p,{alive:false,hp:0,shield:0,energy:17,deaths:1,score:3,deadAt:game.state.tick});await ctx.storage.put("game",game);});
    a.ws.close();await b.next(f=>f.type==="state"&&f.view.hostId===b.id);const restored=await open(name);restored.send({type:"join",playerId:a.id,token:a.token});await restored.next(f=>f.type==="welcome");const state=await restored.state();expect(state.status).toBe("playing");expect(state.view.hostId).toBe(b.id);expect(state.view.players.find((p:any)=>p.id===a.id)).toMatchObject({alive:false,hp:0,energy:17,deaths:1,score:3});restored.action({type:"respawn"});expect((await restored.error()).error).toMatch(/not ready/);b.ws.close();restored.ws.close();
  });
  it("caps simultaneous joins at six without issuing extra identities",async()=>{
    const name=uniq(),clients=await Promise.all(Array.from({length:10},()=>open(name)));for(const c of clients)c.send({type:"join"});const results=await Promise.all(clients.map(c=>c.next(f=>f.type==="welcome"||f.type==="error")));expect(results.filter(f=>f.type==="welcome")).toHaveLength(6);expect(results.filter(f=>f.type==="error"&&f.error.includes("full"))).toHaveLength(4);for(const c of clients)c.ws.close();
  });
  it("bounds unjoined sockets and frees capacity without interrupting the joined host",async()=>{
    const name=uniq(),a=await join(name),idle=[];for(let i=0;i<23;i++)idle.push(await open(name));const blocked=await SELF.fetch(`https://game.test/ws/${name}`,{headers:{Upgrade:"websocket"}});expect(blocked.status).toBe(429);idle[0]!.ws.close();await scheduler.wait(30);const admitted=await open(name);await ready(a);for(const c of idle)c.ws.close();admitted.ws.close();a.ws.close();
  });
  it("rejects binary, oversized actions and nested payloads while a room remains usable",async()=>{
    const a=await join(uniq());a.ws.send(new Uint8Array([1,2,3]));expect((await a.error()).error).toBe("expected a text frame");a.action({type:"ready",ready:true,extra:"x".repeat(5000)});expect((await a.error()).error).toBe("action too large");a.ws.send('{"type":"action","action":{"x":'+"[".repeat(7900)+"0"+"]".repeat(7900)+'}}');expect((await a.error()).error).toBe("action too large");await ready(a);a.ws.close();
  });

  it("preserves live socket identities and host ownership across hibernation",async()=>{
    const name=uniq(),a=await join(name),b=await join(name);await ready(a);const binding=(env as unknown as Env).ROOMS;await evictDurableObject(binding.get(binding.idFromName(name)));await ready(b);a.action({type:"start"});const state=await b.next(f=>f.type==="state"&&f.status==="playing");expect(state.connected).toBe(2);expect(state.view.hostId).toBe(a.id);expect(state.view.players.every((p:any)=>p.connected)).toBe(true);a.ws.close();b.ws.close();
  });

  it("serializes a lobby reset racing with boarding and starts the next sortie cleanly",async()=>{
    const name=uniq(),a=await join(name),b=await join(name);await ready(a);await ready(b);a.action({type:"start"});const active=await a.next(f=>f.type==="state"&&f.status==="playing");const oldSeq=Math.max(...active.view.events.map((e:any)=>e.seq));
    b.action({type:"interact",targetId:"board:"+a.id});a.send({type:"reset"});await a.next(f=>f.type==="state"&&f.status==="lobby"&&f.view.tick===0);await scheduler.wait(130);
    const binding=(env as unknown as Env).ROOMS;await runInDurableObject(binding.get(binding.idFromName(name)),async(_instance,ctx)=>{const game:any=await ctx.storage.get("game");expect(game.state.phase).toBe("lobby");expect(game.state.tick).toBe(0);expect(game.state.npcs).toEqual([]);expect(game.state.projectiles).toEqual([]);expect(game.state.players.every((p:any)=>p.zone==="space"&&!p.ready&&!p.input.fire)).toBe(true);expect(await ctx.storage.getAlarm()).toBeNull();});
    a.frames.length=0;b.frames.length=0;await ready(a);await ready(b);a.action({type:"start"});const again=await a.next(f=>f.type==="state"&&f.status==="playing");expect(again.view.events.find((e:any)=>e.type==="start").seq).toBeGreaterThan(oldSeq);a.ws.close();b.ws.close();
  });
  it("cannot duplicate or resurrect a seat when release races with token reconnect",async()=>{
    for(const reconnectFirst of [false,true]){const name=uniq(),a=await join(name),b=await join(name);b.ws.close();await a.next(f=>f.type==="state"&&f.view.players.find((p:any)=>p.id===b.id)?.connected===false);a.frames.length=0;const replacement=await open(name);const reconnect=()=>replacement.send({type:"join",playerId:b.id,token:b.token});const release=()=>a.action({type:"dismiss",playerId:b.id});if(reconnectFirst){reconnect();release();}else{release();reconnect();}
      const result=await replacement.next(f=>f.type==="welcome"||f.type==="error");if(result.type==="welcome"){expect(result.playerId).toBe(b.id);const state=await a.next(f=>f.type==="state"&&f.view.players.find((p:any)=>p.id===b.id)?.connected);expect(state.seats).toEqual([a.id,b.id]);expect(state.connected).toBe(2);}else{expect(result.error).toBe("unknown reconnect identity");const state=await a.next(f=>f.type==="state"&&f.seats.length===1);expect(state.seats).toEqual([a.id]);}
      a.ws.close();replacement.ws.close();
    }
  });
  it("enforces UTF-8 byte limits and rejects overflowing JSON numbers without corrupting play",async()=>{
    const a=await join(uniq());await ready(a);a.action({type:"start"});await a.next(f=>f.type==="state"&&f.status==="playing");a.action({type:"input",extra:"🚀".repeat(2000)});expect((await a.error()).error).toBe("action too large");
    a.ws.send('{"type":"action","action":{"type":"input","mx":1e309,"my":0,"mz":0,"yaw":0,"pitch":0,"fire":false,"boost":false}}');expect((await a.error()).error).toBe("movement must be finite numbers");a.action({type:"input",mx:0,my:0,mz:0,yaw:1000000,pitch:1.6,fire:false,boost:false});const state=await a.next(f=>f.type==="state"&&f.view.players[0].yaw!==0);expect(Number.isFinite(state.view.players[0].yaw)).toBe(true);expect(Math.abs(state.view.players[0].pitch)).toBeLessThanOrEqual(1.4);a.ws.close();
  });

  it("neutralizes held controls and an active dodge when a live identity changes sockets",async()=>{
    const name=uniq(),a=await join(name);await ready(a);a.action({type:"start"});await a.next(f=>f.type==="state"&&f.status==="playing");a.action({type:"interact",targetId:"own-ship:"+a.id});await a.next(f=>f.type==="state"&&f.view.players[0].zone==="ship:"+a.id);a.action({type:"input",mx:1,my:0,mz:0,yaw:0,pitch:0,fire:true,boost:true});a.action({type:"dash"});await a.next(f=>f.type==="state"&&f.view.players[0].dashing);
    const replacement=await open(name);replacement.send({type:"join",playerId:a.id,token:a.token});expect((await replacement.next(f=>f.type==="welcome")).playerId).toBe(a.id);const restored=await replacement.state(),p=restored.view.players[0];expect(restored.seats).toEqual([a.id]);expect(p).toMatchObject({dashing:false,guard:false,boosting:false,vx:0,vy:0,vz:0});expect(p.dashCooldown).toBeGreaterThan(0);expect(p.energy).toBeLessThan(100);
    const binding=(env as unknown as Env).ROOMS;await evictDurableObject(binding.get(binding.idFromName(name)));const later=await replacement.next(f=>f.type==="state"&&f.view.tick>=restored.view.tick+2);expect(later.view.players[0]).toMatchObject({x:p.x,y:p.y,z:p.z,dashing:false});expect(later.view.events.filter((e:any)=>e.type==="shot"&&e.actorId===a.id&&e.seq>Math.max(...restored.view.events.map((e:any)=>e.seq)))).toEqual([]);replacement.ws.close();a.ws.close();
  });
  it("freezes an empty active room and resumes its private identity with neutral controls",async()=>{
    const name=uniq(),a=await join(name);await ready(a);a.action({type:"start"});await a.next(f=>f.type==="state"&&f.status==="playing");a.action({type:"interact",targetId:"own-ship:"+a.id});await a.next(f=>f.type==="state"&&f.view.players[0].zone==="ship:"+a.id);a.action({type:"input",mx:1,my:0,mz:0,yaw:0,pitch:0,fire:true,boost:true});await a.next(f=>f.type==="state"&&f.view.players[0].x>0);a.ws.close();await scheduler.wait(50);const binding=(env as unknown as Env).ROOMS,stub=binding.get(binding.idFromName(name));
    const paused:any=await runInDurableObject(stub,async(_instance,ctx)=>{const game:any=await ctx.storage.get("game");expect(await ctx.storage.getAlarm()).toBeNull();expect(game.state.players[0].connected).toBe(false);return game.state;});await scheduler.wait(220);await evictDurableObject(stub);const replacement=await open(name);replacement.send({type:"join",playerId:a.id,token:a.token});await replacement.next(f=>f.type==="welcome");const restored=await replacement.state();expect(restored.view.tick).toBe(paused.tick);expect(restored.view.hostId).toBe(a.id);const later=await replacement.next(f=>f.type==="state"&&f.view.tick>=paused.tick+2);expect(later.view.players[0]).toMatchObject({x:paused.players[0].x,y:paused.players[0].y,z:paused.players[0].z,guard:false,boosting:false});expect(later.view.events.filter((e:any)=>e.type==="shot"&&e.actorId===a.id&&e.seq>paused.eventSeq)).toEqual([]);replacement.ws.close();
  });
  it("rejects extreme protocol values without leaking authority or corrupting the active room",async()=>{
    const a=await join(uniq());await ready(a);a.action({type:"start"});await a.next(f=>f.type==="state"&&f.status==="playing");
    for(const raw of ["null","[]",'{"type":"action","action":[]}',...(["mx","my","mz","yaw","pitch"].map(key=>'{"type":"action","action":{"type":"input","mx":0,"my":0,"mz":0,"yaw":0,"pitch":0,"fire":false,"boost":false,"'+key+'":-1e999}}')),'{"type":"action","action":{"type":"input","mx":'+"[".repeat(1000)+"0"+"]".repeat(1000)+',"my":0,"mz":0,"yaw":0,"pitch":0,"fire":false,"boost":false}}']){a.ws.send(raw);expect((await a.error()).error).not.toBe("server error");}
    a.ws.send('{"type":"action","action":{"type":"input","mx":0,"my":0,"mz":0,"yaw":0,"pitch":0,"fire":false,"boost":false,"__proto__":{"polluted":true},"constructor":{"prototype":{"polluted":true}},"playerId":"@system","hp":9999,"score":9999,"state":{"phase":"over"}}}');a.action({type:"equip",weapon:"blade"});const state=await a.next(f=>f.type==="state"&&f.view.players[0].weapon==="blade");expect(state.view.players[0]).toMatchObject({id:a.id,hp:100,score:0});expect(state.status).toBe("playing");expect(({} as any).polluted).toBeUndefined();expect(JSON.stringify(state)).not.toContain(a.token);expect(state.view.players[0].input).toBeUndefined();a.ws.close();
  });

  it("accepts case-insensitive WebSocket upgrade tokens through the main Worker",async()=>{
    for(const upgrade of ["WebSocket","WEBSOCKET"]){const response=await SELF.fetch(`https://game.test/ws/${uniq()}`,{headers:{Upgrade:upgrade}});expect(response.status).toBe(101);const ws=response.webSocket!;ws.accept();ws.close();}
  });

  it("admits five late pilots and reconnects a reserved identity when all six seats are occupied",async()=>{
    const name=uniq(),a=await join(name);await ready(a);a.action({type:"start"});const initial=await a.next(f=>f.type==="state"&&f.status==="playing");const hulls=initial.view.npcs.map((n:any)=>n.maxHp),all=[a];
    for(let i=0;i<5;i++){const c=await join(name,"Late pilot "+i);all.push(c);expect(c.initial.status).toBe("playing");expect(c.initial.view.npcs.map((n:any)=>n.maxHp)).toEqual(hulls);expect(c.initial.view.players.find((p:any)=>p.id===c.id)).toMatchObject({ready:false,alive:true,hp:100,shield:70,energy:100,score:0,launchProtection:10});}
    const reserved=all[2]!;await reserved.next(f=>f.type==="state"&&f.view.tick>=reserved.initial.view.tick+2);reserved.ws.close();await a.next(f=>f.type==="state"&&f.connected===5);const outsider=await open(name);outsider.send({type:"join",name:"Seventh"});expect((await outsider.error()).error).toMatch(/full/);
    const reconnect=await open(name);reconnect.send({type:"join",playerId:reserved.id,token:reserved.token});expect((await reconnect.next(f=>f.type==="welcome")).playerId).toBe(reserved.id);const state=await reconnect.state();expect(state.seats).toHaveLength(6);expect(new Set(state.seats).size).toBe(6);expect(state.connected).toBe(6);expect(state.view.players.find((p:any)=>p.id===reserved.id).launchProtection).toBeLessThan(10);expect(state.view.hostId).toBe(a.id);for(const c of all)c.ws.close();outsider.ws.close();reconnect.ws.close();
  });
  it("changes lobby mode atomically and requires every connected pilot to ready again",async()=>{
    const name=uniq(),a=await join(name,"Commander"),b=await join(name,"Wingmate");await ready(a);await ready(b);b.action({type:"configure",name:"Forged name",mode:"skirmish"});expect((await b.error()).error).toMatch(/host/);a.action({type:"configure",mode:"skirmish"});const changed=await b.next(f=>f.type==="state"&&f.view.mode==="skirmish");expect(changed.view.players.every((p:any)=>!p.ready)).toBe(true);expect(changed.view.players.find((p:any)=>p.id===b.id).name).toBe("Wingmate");a.frames.length=0;b.frames.length=0;a.action({type:"start"});expect((await a.error()).error).toMatch(/ready/);await ready(a);await ready(b);await a.next(f=>f.type==="state"&&f.view.mode==="skirmish"&&f.view.players.every((p:any)=>p.ready));a.action({type:"start"});await b.next(f=>f.type==="state"&&f.status==="playing");a.action({type:"configure",mode:"expedition"});expect((await a.error()).error).toMatch(/lobby/);b.send({type:"reset"});expect((await b.error()).error).toMatch(/host/);b.frames.length=0;a.send({type:"reset"});const lobby=await b.next(f=>f.type==="state"&&f.status==="lobby"&&f.view.mode==="skirmish");expect(lobby.view.players.every((p:any)=>!p.ready)).toBe(true);a.ws.close();b.ws.close();
  });
  // Trusted death fixture isolates duplicate reconstruction requests at their readiness boundary.
  it("commits one reconstruction when duplicate requests arrive together",async()=>{
    const name=uniq(),a=await join(name);await ready(a);a.action({type:"start"});await a.next(f=>f.type==="state"&&f.status==="playing");const binding=(env as unknown as Env).ROOMS,stub=binding.get(binding.idFromName(name));await runInDurableObject(stub,async(_instance,ctx)=>{const game:any=await ctx.storage.get("game");game.state.tick=100;game.state.npcs=[];Object.assign(game.state.players[0],{alive:false,hp:0,shield:0,energy:0,deadAt:50,deaths:1});await ctx.storage.put("game",game);await ctx.storage.deleteAlarm();});a.frames.length=0;
    a.action({type:"respawn"});a.action({type:"respawn"});const state=await a.next(f=>f.type==="state"&&f.view.players[0].alive&&f.view.players[0].deaths===1);expect((await a.error()).error).toMatch(/reconstruction is not ready/);expect(state.view.events.filter((e:any)=>e.type==="spawn"&&e.actorId===a.id)).toHaveLength(1);await runInDurableObject(stub,async(_instance,ctx)=>{const game:any=await ctx.storage.get("game");expect(game.state.players[0]).toMatchObject({alive:true,hp:100,shield:70,energy:100,spawnAt:100,deaths:1});expect(game.state.events.filter((e:any)=>e.type==="spawn")).toHaveLength(1);});a.ws.close();
  });

  it("resolves competing reconnects to one socket without reviving a former host's authority",async()=>{
    const name=uniq(),a=await join(name),b=await join(name);await ready(a);await ready(b);a.ws.close();await b.next(f=>f.type==="state"&&f.view.hostId===b.id);const contenders=await Promise.all([open(name),open(name)]);for(const c of contenders)c.send({type:"join",playerId:a.id,token:a.token});await Promise.all(contenders.map(c=>c.next(f=>f.type==="welcome")));for(let i=0;i<50&&contenders.filter(c=>c.ws.readyState===WebSocket.OPEN).length!==1;i++)await scheduler.wait(10);const live=contenders.filter(c=>c.ws.readyState===WebSocket.OPEN);expect(live).toHaveLength(1);const survivor=live[0]!;
    const binding=(env as unknown as Env).ROOMS;await runInDurableObject(binding.get(binding.idFromName(name)),async(_instance,ctx)=>{const game:any=await ctx.storage.get("game"),conns:any=await ctx.storage.get("conns");expect(game.seats).toEqual([a.id,b.id]);expect(Object.values(conns).sort()).toEqual([a.id,b.id].sort());expect(game.state.hostId).toBe(b.id);});survivor.action({type:"start"});expect((await survivor.error()).error).toMatch(/host/);b.send({type:"reset"});await b.next(f=>f.type==="state"&&f.view.players.every((p:any)=>!p.ready));b.frames.length=0;survivor.frames.length=0;survivor.action({type:"ready",ready:true});b.action({type:"ready",ready:true});const waiting=await b.next(f=>f.type==="state"&&f.view.players.every((p:any)=>p.ready));expect(waiting.status).toBe("lobby");b.action({type:"start"});expect((await survivor.next(f=>f.type==="state"&&f.status==="playing")).view.hostId).toBe(b.id);b.ws.close();for(const c of contenders)c.ws.close();
  });
  it("preserves a visitor's boarded location through owner departure and returns them to their own fighter",async()=>{
    const name=uniq(),a=await join(name),b=await join(name);await ready(a);await ready(b);a.action({type:"start"});await b.next(f=>f.type==="state"&&f.status==="playing");const ownShip=b.initial.view.players.find((p:any)=>p.id===b.id).ship;b.action({type:"interact",targetId:"board:"+a.id});const boarded=await b.next(f=>f.type==="state"&&f.view.players.find((p:any)=>p.id===b.id).zone==="ship:"+a.id);b.ws.close();await a.next(f=>f.type==="state"&&f.view.players.find((p:any)=>p.id===b.id).connected===false);a.ws.close();await scheduler.wait(30);
    const visitor=await open(name);visitor.send({type:"join",playerId:b.id,token:b.token});await visitor.next(f=>f.type==="welcome");const restored=await visitor.state();expect(restored.view.hostId).toBe(b.id);expect(restored.view.players.find((p:any)=>p.id===b.id)).toMatchObject({zone:"ship:"+a.id,x:0,y:0,z:-23,hp:100});const owner=await open(name);owner.send({type:"join",playerId:a.id,token:a.token});await owner.next(f=>f.type==="welcome");expect((await owner.state()).view.hostId).toBe(b.id);await visitor.next(f=>f.type==="state"&&f.view.tick>=boarded.view.tick+8);visitor.action({type:"interact",targetId:"exit:"+a.id});const exited=await visitor.next(f=>f.type==="state"&&f.view.players.find((p:any)=>p.id===b.id).zone==="space");expect(exited.view.players.find((p:any)=>p.id===b.id)).toMatchObject({x:ownShip.x,y:ownShip.y,z:ownShip.z-4});visitor.ws.close();owner.ws.close();
  });
  // Trusted completed-objective fixture isolates the room's terminal alarm behavior.
  it("keeps a finished match quiet through ping, hibernation and late joins until an explicit reset",async()=>{
    const name=uniq(),a=await join(name);await ready(a);a.action({type:"start"});await a.next(f=>f.type==="state"&&f.status==="playing");const binding=(env as unknown as Env).ROOMS,stub=binding.get(binding.idFromName(name));await runInDurableObject(stub,async(_instance,ctx)=>{const game:any=await ctx.storage.get("game");game.state.objective.cores=["ember","veil","dreadnought"];game.state.npcs=[];Object.assign(game.state.players[0],{x:0,y:0,z:-62});await ctx.storage.put("game",game);});a.action({type:"interact",targetId:"extract"});const terminal=await a.next(f=>f.type==="state"&&f.status==="over");a.frames.length=0;let pong=false;a.ws.addEventListener("message",e=>{if(e.data==="__pong")pong=true;});a.ws.send("__ping");await scheduler.wait(240);expect(pong).toBe(true);expect(a.frames.filter(f=>f.type==="state")).toEqual([]);await evictDurableObject(stub);const late=await join(name,"Late observer");expect(late.initial.status).toBe("over");expect(late.initial.view.tick).toBe(terminal.view.tick);expect(late.initial.result).toEqual(terminal.result);late.action({type:"ready",ready:true});expect((await late.error()).error).toMatch(/lobby/);await runInDurableObject(stub,async(_instance,ctx)=>{expect(await ctx.storage.getAlarm()).toBeNull();const game:any=await ctx.storage.get("game");expect(game.state.phase).toBe("over");expect(game.state.projectiles).toEqual([]);});a.frames.length=0;a.send({type:"reset"});const lobby=await a.next(f=>f.type==="state"&&f.status==="lobby");expect(lobby.view.players.every((p:any)=>!p.ready)).toBe(true);a.ws.close();late.ws.close();
  });

});
